#!/usr/bin/env python3
"""Generate the checked-in DevSquad CLI and schema reference."""

from __future__ import annotations

import argparse
import hashlib
import json
from pathlib import Path
import sys


ROOT = Path(__file__).resolve().parents[1]
CORE = ROOT / "plugin/core"
OUTPUT = ROOT / "docs/generated/core-reference.md"
sys.path.insert(0, str(CORE / "src"))

from devsquad.cli import parser as build_parser  # noqa: E402


def command_usages() -> list[str]:
    result: list[str] = []

    def visit(command_parser: argparse.ArgumentParser) -> None:
        for action in command_parser._actions:
            if not isinstance(action, argparse._SubParsersAction):
                continue
            for name in sorted(action.choices):
                child = action.choices[name]
                usage = child.format_usage().strip().removeprefix("usage: ")
                result.append(" ".join(usage.split()))
                visit(child)

    visit(build_parser())
    return result


def schema_rows() -> list[tuple[str, str, str, str]]:
    rows = []
    for path in sorted((CORE / "schemas").glob("*.schema.json")):
        raw = path.read_bytes()
        value = json.loads(raw)
        required = value.get("required", [])
        rows.append((
            path.name,
            value.get("$id", "—"),
            ", ".join(f"`{field}`" for field in required) or "—",
            hashlib.sha256(raw).hexdigest(),
        ))
    return rows


def render() -> str:
    task_example = json.loads(
        (ROOT / "docs/plans/engineering-team/examples/branch-review.json").read_text()
    )
    lines = [
        "<!-- Generated by scripts/generate-core-reference.py; do not edit. -->",
        "# DevSquad core command and schema reference",
        "",
        "Regenerate with `python3 scripts/generate-core-reference.py`; verify with",
        "`python3 scripts/generate-core-reference.py --check`.",
        "",
        "## Command forms",
        "",
    ]
    lines.extend(f"- `{usage}`" for usage in command_usages())
    lines.extend([
        "",
        "## Common command examples",
        "",
        "```bash",
        "squad --version",
        "squad doctor --project-dir \"$PWD\" --json",
        "squad start --task-file task.json --idempotency-key issue-123 --json",
        "squad status RUN_ID --json",
        "squad events RUN_ID --after 0 --limit 100 --json",
        "squad result RUN_ID --json",
        "squad cancel RUN_ID --json",
        "squad resume RUN_ID --recovery-file recovery.json --json",
        "squad setup --host codex --dry-run --json",
        "```",
        "",
        "`RUN_ID`, task paths and recovery evidence are operator-supplied values; the",
        "runtime never infers them from chat history.",
        "",
        "## Packaged JSON schemas",
        "",
        "| File | Identifier | Required top-level fields | SHA-256 |",
        "|---|---|---|---|",
    ])
    for name, identifier, required, digest in schema_rows():
        lines.append(f"| `{name}` | `{identifier}` | {required} | `{digest}` |")
    lines.extend([
        "",
        "## Task-shape example",
        "",
        "This generated copy demonstrates the strict v1 task shape. Replace the",
        "fixture repository, refs, routing files and checks before starting a run.",
        "",
        "```json",
        json.dumps(task_example, indent=2, sort_keys=True),
        "```",
        "",
    ])
    return "\n".join(lines)


def main(argv: list[str] | None = None) -> int:
    arguments = argparse.ArgumentParser()
    arguments.add_argument("--check", action="store_true")
    parsed = arguments.parse_args(argv)
    content = render()
    if parsed.check:
        if not OUTPUT.is_file() or OUTPUT.read_text() != content:
            print(f"generated reference is stale: {OUTPUT}", file=sys.stderr)
            return 1
        print(f"generated reference is current: {OUTPUT}")
        return 0
    OUTPUT.parent.mkdir(parents=True, exist_ok=True)
    OUTPUT.write_text(content)
    print(OUTPUT)
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
